CREATE OR REPLACE VIEW GET_VUELOS_CONFIRMADOS AS
SELECT ITINERARIOS.ID "ITINERARIO_ID",
ITINERARIOS.AVION_ID "AVION_ID",
ITINERARIOS.ESTADO "ESTADO_VUELO",
ITINERARIOS.FECHA_SALIDA_ESTIMADA "FECHA_SALIDA_VUELO", 
ITINERARIOS.FECHA_LLEGADA_ESTIMADA "FECHA_LLEGADA_VUELO",
RUTAS.CANTIDAD_PROMEDIO_HORAS "PROMEDIO_HORAS_VUELO",
VUELOS.NUMERO_VUELO "NUMERO_VUELO",
ITINERARIOS.PASAJEROS_ECONOMICA "NUMERO_PASAJEROS_ECONOMICA",
ITINERARIOS.PASAJEROS_EJECUTIVA "NUMERO_PASAJEROS_EJECUTIVA",
(NVL(ITINERARIOS.PASAJEROS_ECONOMICA,0) + NVL(ITINERARIOS.PASAJEROS_EJECUTIVA,0)) "NUMERO_TOTAL_PASAJEROS",
AEROPUERTOS_ORIGEN.ID "AEROPUERTO_ORIGEN_ID",
AEROPUERTOS_ORIGEN.NOMBRE "AEROPUERTO_ORIGEN",
AEROPUERTOS_ORIGEN.CIUDAD "CIUDAD_ORIGEN",
AEROPUERTOS_DESTINO.ID "AEROPUERTO_DESTINO_ID",
AEROPUERTOS_DESTINO.NOMBRE "AEROPUERTO_DESTINO",
AEROPUERTOS_DESTINO.CIUDAD "CIUDAD_DESTINO",
AVIONES.ESTADO "AVION_ESTADO",
MODELOS_AVIONES.CAPACIDAD_EJECUTIVA "AVION_CAPACIDAD_EJECUTIVA",
MODELOS_AVIONES.CAPACIDAD_ECONOMICA "AVION_CAPACIDAD_ECONOMICA",
(NVL(MODELOS_AVIONES.CAPACIDAD_ECONOMICA,0) + NVL(MODELOS_AVIONES.CAPACIDAD_EJECUTIVA,0)) "CAPACIDAD_TOTAL"
FROM ITINERARIOS
INNER JOIN VUELOS ON ITINERARIOS.VUELO_ID = VUELOS.ID
INNER JOIN RUTAS ON RUTAS.ID = VUELOS.RUTA_ID
INNER JOIN AEROPUERTOS AEROPUERTOS_ORIGEN ON RUTAS.AEROPUERTO_ORIGEN_ID = AEROPUERTOS_ORIGEN.ID
INNER JOIN AEROPUERTOS AEROPUERTOS_DESTINO ON RUTAS.AEROPUERTO_DESTINO_ID = AEROPUERTOS_DESTINO.ID
LEFT OUTER JOIN AVIONES ON AVIONES.ID = ITINERARIOS.AVION_ID
LEFT OUTER JOIN MODELOS_AVIONES ON AVIONES.MODELO_AVION_ID = MODELOS_AVIONES.ID
WHERE ITINERARIOS.ESTADO IN ('Confirmado','Programado')
ORDER BY ITINERARIOS.FECHA_LLEGADA_ESTIMADA DESC;



---- PROCEDIMIENTO CREADO SOLAMENTE PARA ORGANIZAR FECHAS PARA PRUEBAS DEL EJERCICIO
CREATE OR REPLACE PROCEDURE ORGANIZAR_FECHAS_VUELOS AS 
    ROW_COUNT NUMBER;
    FECHA_LLEG_TO_UP ITINERARIOS.FECHA_SALIDA_ESTIMADA%TYPE; 
    ROUND_ROWS NUMBER;
BEGIN
    SELECT DISTINCT COUNT(*) INTO ROW_COUNT
    FROM GET_VUELOS_CONFIRMADOS WHERE AEROPUERTO_DESTINO_ID IN(SELECT AEROPUERTO_ORIGEN_ID FROM GET_VUELOS_CONFIRMADOS WHERE ITINERARIO_ID BETWEEN 50000 AND 50021);
    SELECT FECHA_SALIDA_VUELO INTO FECHA_LLEG_TO_UP FROM GET_VUELOS_CONFIRMADOS WHERE ITINERARIO_ID = 50000;
    
    ROUND_ROWS := ROUND(ROW_COUNT/5); 
    
    FOR D IN 0..ROUND_ROWS LOOP
                    
                    MERGE
                    INTO ITINERARIOS trg
                    USING (
                        SELECT DISTINCT OU_AE.ITINERARIO_ID "ID_ITINERARIO"
                        ,(FECHA_LLEG_TO_UP + ((select round(dbms_random.value(-10, -2)) + 1 from dual)/24)) "FECHA_LLEG_ACTUA_",
                        ((FECHA_LLEG_TO_UP + ((select round(dbms_random.value(-10, -2)) + 1 from dual)/24)) -
                        (OU_AE.PROMEDIO_HORAS_VUELO/24)) "FECHA_SALI_TO_UP"
                        FROM GET_VUELOS_CONFIRMADOS OU_AE WHERE OU_AE.AEROPUERTO_DESTINO_ID IN(SELECT IN_AE.AEROPUERTO_ORIGEN_ID FROM 
                        GET_VUELOS_CONFIRMADOS IN_AE WHERE IN_AE.ITINERARIO_ID BETWEEN 50000 AND 50021)
                        ORDER BY OU_AE.ITINERARIO_ID
                        OFFSET D ROWS FETCH NEXT 1 ROWS ONLY
                    )src
                    ON (trg.ID = src."ID_ITINERARIO")
                    WHEN MATCHED THEN 
                    UPDATE SET trg.FECHA_LLEGADA_ESTIMADA = src."FECHA_LLEG_ACTUA_",
                           trg.FECHA_LLEGADA_REAL = src."FECHA_LLEG_ACTUA_",
                           trg.FECHA_SALIDA_ESTIMADA = src."FECHA_SALI_TO_UP",
                           trg.FECHA_SALIDA_REAL = src."FECHA_SALI_TO_UP";                                     
                                    
    END LOOP;
    
    DBMS_OUTPUT.put_line(ROW_COUNT || ' '  || FECHA_LLEG_TO_UP || ' ' || ROUND_ROWS);
END; 
COMMIT WORK;


--- Este llamado del store procedure es necesario para organizar que algunos vuelos ingresados para la prueba tenga relacion con las fechas de otros vuelos
--por favor ejecutar este store procedure
---EXEC ORGANIZAR_FECHAS_VUELOS;

CREATE OR REPLACE FUNCTION ASIGNAR_AVION(ITINERARIO_ID_PARAMETER IN NUMBER) RETURN NUMBER 
IS isSUCCESS NUMBER;
   ITINERARIO_SELECT_VUELO ITINERARIOS.ID%TYPE;
   ITINERARIO_AEROP_SALIDA_ID AEROPUERTOS.ID%TYPE;
   ITINERARIO_FECHA_SALIDA ITINERARIOS.FECHA_SALIDA_ESTIMADA%TYPE;
   ITINERARIO_SELECT_FEC_LLEG ITINERARIOS.FECHA_LLEGADA_ESTIMADA%TYPE;
   DIFERENCIA_FECHAS NUMBER;
   ESTADO_AVION AVIONES.ESTADO%TYPE;
   TO_SELECT_AVION_ID AVIONES.ID%TYPE;
   STEP NUMBER;
BEGIN
        STEP := 0;
        --- BUESQUEDA DEL VUELO PASADO COMO PARAMETRO
        SELECT AEROPUERTO_ORIGEN_ID, FECHA_SALIDA_VUELO
        INTO ITINERARIO_AEROP_SALIDA_ID, ITINERARIO_FECHA_SALIDA 
        FROM GET_VUELOS_CONFIRMADOS WHERE ITINERARIO_ID = ITINERARIO_ID_PARAMETER AND AVION_ID IS NULL AND ESTADO_VUELO = 'Programado'; 
        
        STEP := 1;
        --BUESQUEDA DEL VUELO QUE COINCIDA CON EL AEROPUERTO DE DESTINO IGUAL QUE EL DE ORIGEN DEL VUELO BUSCADO ANTERIORMENTE
        -- ADEMAS QUE EL VUELO TENGA UN AVION ASIGNADO Y QUE LA FECHA ENTRE VUELOS ESTE 2 Y 12 HORAS DE DIFERENCIA Y QUE EL AVION PUEDA
        -- SER ASIGNADO OSEA EN ESTADO VUELO O TIERRA
        SELECT ITINERARIO_ID , TRUNC((ITINERARIO_FECHA_SALIDA - FECHA_LLEGADA_VUELO) * (24)),
        FECHA_LLEGADA_VUELO, AVION_ESTADO, AVION_ID
        INTO ITINERARIO_SELECT_VUELO , DIFERENCIA_FECHAS, ITINERARIO_SELECT_FEC_LLEG, ESTADO_AVION,
        TO_SELECT_AVION_ID
        FROM GET_VUELOS_CONFIRMADOS 
        WHERE AEROPUERTO_DESTINO_ID = ITINERARIO_AEROP_SALIDA_ID 
        --AND TO_CHAR(FECHA_LLEGADA_VUELO, 'MM-DD-YYYY') = TO_CHAR(ITINERARIO_FECHA_SALIDA, 'MM-DD-YYYY')
        AND AVION_ID IS NOT NULL
        AND TRUNC((ITINERARIO_FECHA_SALIDA - FECHA_LLEGADA_VUELO) * (24)) >= 2 
        AND TRUNC((ITINERARIO_FECHA_SALIDA - FECHA_LLEGADA_VUELO) * (24)) <= 12
        AND AVION_ESTADO IN ('Vuelo','Tierra')
        OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;

        STEP := 2;
        --ACTUALIZAION DEL VUELO
        UPDATE ITINERARIOS SET AVION_ID = TO_SELECT_AVION_ID WHERE ID = ITINERARIO_ID_PARAMETER;
        
IF SQL%FOUND THEN
     isSUCCESS := 1;
     DBMS_OUTPUT.put_line('VUELO A CONFIRMAR: ' || ITINERARIO_ID_PARAMETER || ', FECHA DE SALIDA: ' || ITINERARIO_FECHA_SALIDA 
                          || ', AEROPUERTO DE SALIDA ID: ' || ITINERARIO_AEROP_SALIDA_ID);
     DBMS_OUTPUT.put_line('VUELO A SELECCIONADO: ' || ITINERARIO_SELECT_VUELO || ', FECHA DE LLEGADA : ' || ITINERARIO_SELECT_FEC_LLEG
                       || ', AVION ID: '  || TO_SELECT_AVION_ID || ', ESTADO DEL AVION: ' || ESTADO_AVION); 
     DBMS_OUTPUT.put_line('DIFERENCIA DE HORAS ENTRE LOS VUELOS: ' || DIFERENCIA_FECHAS);
     DBMS_OUTPUT.put_line('SE ACTUALIZÓ EL VUELO: ' || ITINERARIO_ID_PARAMETER || ' CON EL AVION: ' || TO_SELECT_AVION_ID);
     RETURN isSUCCESS;
END IF; 

EXCEPTION
        WHEN NO_DATA_FOUND THEN
            isSUCCESS := 0;
            IF STEP = 0 THEN
                 DBMS_OUTPUT.put_line('EL VUELO: '|| ITINERARIO_ID_PARAMETER || ' NO SE ENCONTRO O YA POSEE UN AVION ASIGNADO O NO ESTA PROGRAMADO');
            ELSIF STEP = 1 THEN   
                DBMS_OUTPUT.put_line('NO SE ENCONTRARON VUELOS QUE SE DIRIGAN AL AEROPUERTO DEL VUELO: '|| ITINERARIO_ID_PARAMETER || ' EL MISMO DIA CON 2 HORAS COMO MINIMO DE DIFERENCIA');
            ELSE  
                DBMS_OUTPUT.put_line('DATA NO FOUND');
            END IF;  
        RETURN isSUCCESS;

END ASIGNAR_AVION;

